name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    #Dependency installations
    - name: Install dependencies
      run: yarn
      
    #Run the build
    - name: Run build
      run: yarn build
    
    #Copy files do Digital Ocean
    - name: copy dist to digital ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gobarber-backend-nodejs-prod"
    
    #Run production scripts
    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-backend-nodejs-prod
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-api




